// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package im

/*
protoc --go_out=. message.proto
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserProfileResponseMsg_Result int32

const (
	UserProfileResponseMsg_Success      UserProfileResponseMsg_Result = 0
	UserProfileResponseMsg_NoPermission UserProfileResponseMsg_Result = 1
	UserProfileResponseMsg_Unspecified  UserProfileResponseMsg_Result = 2
)

var UserProfileResponseMsg_Result_name = map[int32]string{
	0: "Success",
	1: "NoPermission",
	2: "Unspecified",
}
var UserProfileResponseMsg_Result_value = map[string]int32{
	"Success":      0,
	"NoPermission": 1,
	"Unspecified":  2,
}

func (x UserProfileResponseMsg_Result) String() string {
	return proto.EnumName(UserProfileResponseMsg_Result_name, int32(x))
}
func (UserProfileResponseMsg_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{7, 0}
}

type UpdateProfileResponseMsg_Result int32

const (
	UpdateProfileResponseMsg_Success       UpdateProfileResponseMsg_Result = 0
	UpdateProfileResponseMsg_UserNotExists UpdateProfileResponseMsg_Result = 1
	UpdateProfileResponseMsg_Unspecified   UpdateProfileResponseMsg_Result = 2
)

var UpdateProfileResponseMsg_Result_name = map[int32]string{
	0: "Success",
	1: "UserNotExists",
	2: "Unspecified",
}
var UpdateProfileResponseMsg_Result_value = map[string]int32{
	"Success":       0,
	"UserNotExists": 1,
	"Unspecified":   2,
}

func (x UpdateProfileResponseMsg_Result) String() string {
	return proto.EnumName(UpdateProfileResponseMsg_Result_name, int32(x))
}
func (UpdateProfileResponseMsg_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{9, 0}
}

type FriendResponseMsg_Result int32

const (
	FriendResponseMsg_Success       FriendResponseMsg_Result = 0
	FriendResponseMsg_UserNotExists FriendResponseMsg_Result = 1
	FriendResponseMsg_Unspecified   FriendResponseMsg_Result = 2
)

var FriendResponseMsg_Result_name = map[int32]string{
	0: "Success",
	1: "UserNotExists",
	2: "Unspecified",
}
var FriendResponseMsg_Result_value = map[string]int32{
	"Success":       0,
	"UserNotExists": 1,
	"Unspecified":   2,
}

func (x FriendResponseMsg_Result) String() string {
	return proto.EnumName(FriendResponseMsg_Result_name, int32(x))
}
func (FriendResponseMsg_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{11, 0}
}

type ApproveResponseMsg_Result int32

const (
	ApproveResponseMsg_Success          ApproveResponseMsg_Result = 0
	ApproveResponseMsg_RequestNotExists ApproveResponseMsg_Result = 1
	ApproveResponseMsg_AlreadyApproved  ApproveResponseMsg_Result = 2
	ApproveResponseMsg_Unspecified      ApproveResponseMsg_Result = 3
)

var ApproveResponseMsg_Result_name = map[int32]string{
	0: "Success",
	1: "RequestNotExists",
	2: "AlreadyApproved",
	3: "Unspecified",
}
var ApproveResponseMsg_Result_value = map[string]int32{
	"Success":          0,
	"RequestNotExists": 1,
	"AlreadyApproved":  2,
	"Unspecified":      3,
}

func (x ApproveResponseMsg_Result) String() string {
	return proto.EnumName(ApproveResponseMsg_Result_name, int32(x))
}
func (ApproveResponseMsg_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{13, 0}
}

type GetAllRequestsResponseMsg_Result int32

const (
	GetAllRequestsResponseMsg_Success     GetAllRequestsResponseMsg_Result = 0
	GetAllRequestsResponseMsg_Unspecified GetAllRequestsResponseMsg_Result = 1
)

var GetAllRequestsResponseMsg_Result_name = map[int32]string{
	0: "Success",
	1: "Unspecified",
}
var GetAllRequestsResponseMsg_Result_value = map[string]int32{
	"Success":     0,
	"Unspecified": 1,
}

func (x GetAllRequestsResponseMsg_Result) String() string {
	return proto.EnumName(GetAllRequestsResponseMsg_Result_name, int32(x))
}
func (GetAllRequestsResponseMsg_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{16, 0}
}

type TextMsgResponse_Result int32

const (
	TextMsgResponse_Success       TextMsgResponse_Result = 0
	TextMsgResponse_UserNotExists TextMsgResponse_Result = 1
	TextMsgResponse_NotFriend     TextMsgResponse_Result = 2
	TextMsgResponse_Unspecified   TextMsgResponse_Result = 3
)

var TextMsgResponse_Result_name = map[int32]string{
	0: "Success",
	1: "UserNotExists",
	2: "NotFriend",
	3: "Unspecified",
}
var TextMsgResponse_Result_value = map[string]int32{
	"Success":       0,
	"UserNotExists": 1,
	"NotFriend":     2,
	"Unspecified":   3,
}

func (x TextMsgResponse_Result) String() string {
	return proto.EnumName(TextMsgResponse_Result_name, int32(x))
}
func (TextMsgResponse_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{19, 0}
}

type GetAllCachedMessagesResponse_Result int32

const (
	GetAllCachedMessagesResponse_Success     GetAllCachedMessagesResponse_Result = 0
	GetAllCachedMessagesResponse_Unspecified GetAllCachedMessagesResponse_Result = 1
)

var GetAllCachedMessagesResponse_Result_name = map[int32]string{
	0: "Success",
	1: "Unspecified",
}
var GetAllCachedMessagesResponse_Result_value = map[string]int32{
	"Success":     0,
	"Unspecified": 1,
}

func (x GetAllCachedMessagesResponse_Result) String() string {
	return proto.EnumName(GetAllCachedMessagesResponse_Result_name, int32(x))
}
func (GetAllCachedMessagesResponse_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{21, 0}
}

type Header struct {
	// address base58 encoded
	CheckSum             uint32   `protobuf:"varint,1,opt,name=checkSum,proto3" json:"checkSum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetCheckSum() uint32 {
	if m != nil {
		return m.CheckSum
	}
	return 0
}

type HeartbeatMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatMsg) Reset()         { *m = HeartbeatMsg{} }
func (m *HeartbeatMsg) String() string { return proto.CompactTextString(m) }
func (*HeartbeatMsg) ProtoMessage()    {}
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{1}
}
func (m *HeartbeatMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatMsg.Unmarshal(m, b)
}
func (m *HeartbeatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatMsg.Marshal(b, m, deterministic)
}
func (dst *HeartbeatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatMsg.Merge(dst, src)
}
func (m *HeartbeatMsg) XXX_Size() int {
	return xxx_messageInfo_HeartbeatMsg.Size(m)
}
func (m *HeartbeatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatMsg proto.InternalMessageInfo

func (m *HeartbeatMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type InfoMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoMsg) Reset()         { *m = InfoMsg{} }
func (m *InfoMsg) String() string { return proto.CompactTextString(m) }
func (*InfoMsg) ProtoMessage()    {}
func (*InfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{2}
}
func (m *InfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoMsg.Unmarshal(m, b)
}
func (m *InfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoMsg.Marshal(b, m, deterministic)
}
func (dst *InfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoMsg.Merge(dst, src)
}
func (m *InfoMsg) XXX_Size() int {
	return xxx_messageInfo_InfoMsg.Size(m)
}
func (m *InfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InfoMsg proto.InternalMessageInfo

func (m *InfoMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *InfoMsg) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type LoginMsg1 struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMsg1) Reset()         { *m = LoginMsg1{} }
func (m *LoginMsg1) String() string { return proto.CompactTextString(m) }
func (*LoginMsg1) ProtoMessage()    {}
func (*LoginMsg1) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{3}
}
func (m *LoginMsg1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsg1.Unmarshal(m, b)
}
func (m *LoginMsg1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsg1.Marshal(b, m, deterministic)
}
func (dst *LoginMsg1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsg1.Merge(dst, src)
}
func (m *LoginMsg1) XXX_Size() int {
	return xxx_messageInfo_LoginMsg1.Size(m)
}
func (m *LoginMsg1) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsg1.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsg1 proto.InternalMessageInfo

func (m *LoginMsg1) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LoginMsg1) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type LoginMsg2 struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EncryptedText        []byte   `protobuf:"bytes,2,opt,name=encryptedText,proto3" json:"encryptedText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMsg2) Reset()         { *m = LoginMsg2{} }
func (m *LoginMsg2) String() string { return proto.CompactTextString(m) }
func (*LoginMsg2) ProtoMessage()    {}
func (*LoginMsg2) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{4}
}
func (m *LoginMsg2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsg2.Unmarshal(m, b)
}
func (m *LoginMsg2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsg2.Marshal(b, m, deterministic)
}
func (dst *LoginMsg2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsg2.Merge(dst, src)
}
func (m *LoginMsg2) XXX_Size() int {
	return xxx_messageInfo_LoginMsg2.Size(m)
}
func (m *LoginMsg2) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsg2.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsg2 proto.InternalMessageInfo

func (m *LoginMsg2) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LoginMsg2) GetEncryptedText() []byte {
	if m != nil {
		return m.EncryptedText
	}
	return nil
}

// for test usage
type LoginMsg3 struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	DecryptedText        []byte   `protobuf:"bytes,2,opt,name=decryptedText,proto3" json:"decryptedText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMsg3) Reset()         { *m = LoginMsg3{} }
func (m *LoginMsg3) String() string { return proto.CompactTextString(m) }
func (*LoginMsg3) ProtoMessage()    {}
func (*LoginMsg3) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{5}
}
func (m *LoginMsg3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsg3.Unmarshal(m, b)
}
func (m *LoginMsg3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsg3.Marshal(b, m, deterministic)
}
func (dst *LoginMsg3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsg3.Merge(dst, src)
}
func (m *LoginMsg3) XXX_Size() int {
	return xxx_messageInfo_LoginMsg3.Size(m)
}
func (m *LoginMsg3) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsg3.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsg3 proto.InternalMessageInfo

func (m *LoginMsg3) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LoginMsg3) GetDecryptedText() []byte {
	if m != nil {
		return m.DecryptedText
	}
	return nil
}

type UserProfileRequestMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfileRequestMsg) Reset()         { *m = UserProfileRequestMsg{} }
func (m *UserProfileRequestMsg) String() string { return proto.CompactTextString(m) }
func (*UserProfileRequestMsg) ProtoMessage()    {}
func (*UserProfileRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{6}
}
func (m *UserProfileRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileRequestMsg.Unmarshal(m, b)
}
func (m *UserProfileRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileRequestMsg.Marshal(b, m, deterministic)
}
func (dst *UserProfileRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileRequestMsg.Merge(dst, src)
}
func (m *UserProfileRequestMsg) XXX_Size() int {
	return xxx_messageInfo_UserProfileRequestMsg.Size(m)
}
func (m *UserProfileRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileRequestMsg proto.InternalMessageInfo

func (m *UserProfileRequestMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UserProfileRequestMsg) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UserProfileResponseMsg struct {
	Header               *Header                       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result               UserProfileResponseMsg_Result `protobuf:"varint,2,opt,name=result,proto3,enum=im.UserProfileResponseMsg_Result" json:"result,omitempty"`
	UserID               string                        `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	PublicKey            string                        `protobuf:"bytes,4,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	DisplayName          string                        `protobuf:"bytes,5,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Description          string                        `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Avatar               []byte                        `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UserProfileResponseMsg) Reset()         { *m = UserProfileResponseMsg{} }
func (m *UserProfileResponseMsg) String() string { return proto.CompactTextString(m) }
func (*UserProfileResponseMsg) ProtoMessage()    {}
func (*UserProfileResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{7}
}
func (m *UserProfileResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileResponseMsg.Unmarshal(m, b)
}
func (m *UserProfileResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileResponseMsg.Marshal(b, m, deterministic)
}
func (dst *UserProfileResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileResponseMsg.Merge(dst, src)
}
func (m *UserProfileResponseMsg) XXX_Size() int {
	return xxx_messageInfo_UserProfileResponseMsg.Size(m)
}
func (m *UserProfileResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileResponseMsg proto.InternalMessageInfo

func (m *UserProfileResponseMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UserProfileResponseMsg) GetResult() UserProfileResponseMsg_Result {
	if m != nil {
		return m.Result
	}
	return UserProfileResponseMsg_Success
}

func (m *UserProfileResponseMsg) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserProfileResponseMsg) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *UserProfileResponseMsg) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UserProfileResponseMsg) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UserProfileResponseMsg) GetAvatar() []byte {
	if m != nil {
		return m.Avatar
	}
	return nil
}

type UpdateProfileRequestMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Avatar               []byte   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProfileRequestMsg) Reset()         { *m = UpdateProfileRequestMsg{} }
func (m *UpdateProfileRequestMsg) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileRequestMsg) ProtoMessage()    {}
func (*UpdateProfileRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{8}
}
func (m *UpdateProfileRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileRequestMsg.Unmarshal(m, b)
}
func (m *UpdateProfileRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileRequestMsg.Marshal(b, m, deterministic)
}
func (dst *UpdateProfileRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileRequestMsg.Merge(dst, src)
}
func (m *UpdateProfileRequestMsg) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileRequestMsg.Size(m)
}
func (m *UpdateProfileRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileRequestMsg proto.InternalMessageInfo

func (m *UpdateProfileRequestMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UpdateProfileRequestMsg) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UpdateProfileRequestMsg) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateProfileRequestMsg) GetAvatar() []byte {
	if m != nil {
		return m.Avatar
	}
	return nil
}

type UpdateProfileResponseMsg struct {
	Header               *Header                         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result               UpdateProfileResponseMsg_Result `protobuf:"varint,2,opt,name=result,proto3,enum=im.UpdateProfileResponseMsg_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateProfileResponseMsg) Reset()         { *m = UpdateProfileResponseMsg{} }
func (m *UpdateProfileResponseMsg) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileResponseMsg) ProtoMessage()    {}
func (*UpdateProfileResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{9}
}
func (m *UpdateProfileResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileResponseMsg.Unmarshal(m, b)
}
func (m *UpdateProfileResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileResponseMsg.Marshal(b, m, deterministic)
}
func (dst *UpdateProfileResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileResponseMsg.Merge(dst, src)
}
func (m *UpdateProfileResponseMsg) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileResponseMsg.Size(m)
}
func (m *UpdateProfileResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileResponseMsg proto.InternalMessageInfo

func (m *UpdateProfileResponseMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UpdateProfileResponseMsg) GetResult() UpdateProfileResponseMsg_Result {
	if m != nil {
		return m.Result
	}
	return UpdateProfileResponseMsg_Success
}

type FriendRequestMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	FriendUserID         string   `protobuf:"bytes,2,opt,name=friendUserID,proto3" json:"friendUserID,omitempty"`
	HelloMsg             string   `protobuf:"bytes,3,opt,name=helloMsg,proto3" json:"helloMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendRequestMsg) Reset()         { *m = FriendRequestMsg{} }
func (m *FriendRequestMsg) String() string { return proto.CompactTextString(m) }
func (*FriendRequestMsg) ProtoMessage()    {}
func (*FriendRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{10}
}
func (m *FriendRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRequestMsg.Unmarshal(m, b)
}
func (m *FriendRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRequestMsg.Marshal(b, m, deterministic)
}
func (dst *FriendRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRequestMsg.Merge(dst, src)
}
func (m *FriendRequestMsg) XXX_Size() int {
	return xxx_messageInfo_FriendRequestMsg.Size(m)
}
func (m *FriendRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRequestMsg proto.InternalMessageInfo

func (m *FriendRequestMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *FriendRequestMsg) GetFriendUserID() string {
	if m != nil {
		return m.FriendUserID
	}
	return ""
}

func (m *FriendRequestMsg) GetHelloMsg() string {
	if m != nil {
		return m.HelloMsg
	}
	return ""
}

type FriendResponseMsg struct {
	Header               *Header                  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result               FriendResponseMsg_Result `protobuf:"varint,2,opt,name=result,proto3,enum=im.FriendResponseMsg_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FriendResponseMsg) Reset()         { *m = FriendResponseMsg{} }
func (m *FriendResponseMsg) String() string { return proto.CompactTextString(m) }
func (*FriendResponseMsg) ProtoMessage()    {}
func (*FriendResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{11}
}
func (m *FriendResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendResponseMsg.Unmarshal(m, b)
}
func (m *FriendResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendResponseMsg.Marshal(b, m, deterministic)
}
func (dst *FriendResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendResponseMsg.Merge(dst, src)
}
func (m *FriendResponseMsg) XXX_Size() int {
	return xxx_messageInfo_FriendResponseMsg.Size(m)
}
func (m *FriendResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FriendResponseMsg proto.InternalMessageInfo

func (m *FriendResponseMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *FriendResponseMsg) GetResult() FriendResponseMsg_Result {
	if m != nil {
		return m.Result
	}
	return FriendResponseMsg_Success
}

type ApproveRequestMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	FriendUserID         string   `protobuf:"bytes,2,opt,name=friendUserID,proto3" json:"friendUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveRequestMsg) Reset()         { *m = ApproveRequestMsg{} }
func (m *ApproveRequestMsg) String() string { return proto.CompactTextString(m) }
func (*ApproveRequestMsg) ProtoMessage()    {}
func (*ApproveRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{12}
}
func (m *ApproveRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveRequestMsg.Unmarshal(m, b)
}
func (m *ApproveRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveRequestMsg.Marshal(b, m, deterministic)
}
func (dst *ApproveRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveRequestMsg.Merge(dst, src)
}
func (m *ApproveRequestMsg) XXX_Size() int {
	return xxx_messageInfo_ApproveRequestMsg.Size(m)
}
func (m *ApproveRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveRequestMsg proto.InternalMessageInfo

func (m *ApproveRequestMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ApproveRequestMsg) GetFriendUserID() string {
	if m != nil {
		return m.FriendUserID
	}
	return ""
}

type ApproveResponseMsg struct {
	Header               *Header                   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result               ApproveResponseMsg_Result `protobuf:"varint,2,opt,name=result,proto3,enum=im.ApproveResponseMsg_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ApproveResponseMsg) Reset()         { *m = ApproveResponseMsg{} }
func (m *ApproveResponseMsg) String() string { return proto.CompactTextString(m) }
func (*ApproveResponseMsg) ProtoMessage()    {}
func (*ApproveResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{13}
}
func (m *ApproveResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveResponseMsg.Unmarshal(m, b)
}
func (m *ApproveResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveResponseMsg.Marshal(b, m, deterministic)
}
func (dst *ApproveResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveResponseMsg.Merge(dst, src)
}
func (m *ApproveResponseMsg) XXX_Size() int {
	return xxx_messageInfo_ApproveResponseMsg.Size(m)
}
func (m *ApproveResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveResponseMsg proto.InternalMessageInfo

func (m *ApproveResponseMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ApproveResponseMsg) GetResult() ApproveResponseMsg_Result {
	if m != nil {
		return m.Result
	}
	return ApproveResponseMsg_Success
}

type GetAllRequestsMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequestsMsg) Reset()         { *m = GetAllRequestsMsg{} }
func (m *GetAllRequestsMsg) String() string { return proto.CompactTextString(m) }
func (*GetAllRequestsMsg) ProtoMessage()    {}
func (*GetAllRequestsMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{14}
}
func (m *GetAllRequestsMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequestsMsg.Unmarshal(m, b)
}
func (m *GetAllRequestsMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequestsMsg.Marshal(b, m, deterministic)
}
func (dst *GetAllRequestsMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequestsMsg.Merge(dst, src)
}
func (m *GetAllRequestsMsg) XXX_Size() int {
	return xxx_messageInfo_GetAllRequestsMsg.Size(m)
}
func (m *GetAllRequestsMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequestsMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequestsMsg proto.InternalMessageInfo

func (m *GetAllRequestsMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type Request struct {
	FromID               string   `protobuf:"bytes,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	HelloMsg             string   `protobuf:"bytes,2,opt,name=helloMsg,proto3" json:"helloMsg,omitempty"`
	IsApproved           bool     `protobuf:"varint,3,opt,name=isApproved,proto3" json:"isApproved,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{15}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetFromID() string {
	if m != nil {
		return m.FromID
	}
	return ""
}

func (m *Request) GetHelloMsg() string {
	if m != nil {
		return m.HelloMsg
	}
	return ""
}

func (m *Request) GetIsApproved() bool {
	if m != nil {
		return m.IsApproved
	}
	return false
}

func (m *Request) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type GetAllRequestsResponseMsg struct {
	Header               *Header                          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result               GetAllRequestsResponseMsg_Result `protobuf:"varint,2,opt,name=result,proto3,enum=im.GetAllRequestsResponseMsg_Result" json:"result,omitempty"`
	Requests             []*Request                       `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GetAllRequestsResponseMsg) Reset()         { *m = GetAllRequestsResponseMsg{} }
func (m *GetAllRequestsResponseMsg) String() string { return proto.CompactTextString(m) }
func (*GetAllRequestsResponseMsg) ProtoMessage()    {}
func (*GetAllRequestsResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{16}
}
func (m *GetAllRequestsResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequestsResponseMsg.Unmarshal(m, b)
}
func (m *GetAllRequestsResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequestsResponseMsg.Marshal(b, m, deterministic)
}
func (dst *GetAllRequestsResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequestsResponseMsg.Merge(dst, src)
}
func (m *GetAllRequestsResponseMsg) XXX_Size() int {
	return xxx_messageInfo_GetAllRequestsResponseMsg.Size(m)
}
func (m *GetAllRequestsResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequestsResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequestsResponseMsg proto.InternalMessageInfo

func (m *GetAllRequestsResponseMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetAllRequestsResponseMsg) GetResult() GetAllRequestsResponseMsg_Result {
	if m != nil {
		return m.Result
	}
	return GetAllRequestsResponseMsg_Success
}

func (m *GetAllRequestsResponseMsg) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type Text struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	SendTime             string   `protobuf:"bytes,3,opt,name=SendTime,proto3" json:"SendTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{17}
}
func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (dst *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(dst, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Text) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Text) GetSendTime() string {
	if m != nil {
		return m.SendTime
	}
	return ""
}

type TextMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Text                 *Text    `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextMsg) Reset()         { *m = TextMsg{} }
func (m *TextMsg) String() string { return proto.CompactTextString(m) }
func (*TextMsg) ProtoMessage()    {}
func (*TextMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{18}
}
func (m *TextMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextMsg.Unmarshal(m, b)
}
func (m *TextMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextMsg.Marshal(b, m, deterministic)
}
func (dst *TextMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextMsg.Merge(dst, src)
}
func (m *TextMsg) XXX_Size() int {
	return xxx_messageInfo_TextMsg.Size(m)
}
func (m *TextMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TextMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TextMsg proto.InternalMessageInfo

func (m *TextMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TextMsg) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

// get cached messages
type TextMsgResponse struct {
	Header               *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result               TextMsgResponse_Result `protobuf:"varint,2,opt,name=result,proto3,enum=im.TextMsgResponse_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TextMsgResponse) Reset()         { *m = TextMsgResponse{} }
func (m *TextMsgResponse) String() string { return proto.CompactTextString(m) }
func (*TextMsgResponse) ProtoMessage()    {}
func (*TextMsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{19}
}
func (m *TextMsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextMsgResponse.Unmarshal(m, b)
}
func (m *TextMsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextMsgResponse.Marshal(b, m, deterministic)
}
func (dst *TextMsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextMsgResponse.Merge(dst, src)
}
func (m *TextMsgResponse) XXX_Size() int {
	return xxx_messageInfo_TextMsgResponse.Size(m)
}
func (m *TextMsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TextMsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TextMsgResponse proto.InternalMessageInfo

func (m *TextMsgResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TextMsgResponse) GetResult() TextMsgResponse_Result {
	if m != nil {
		return m.Result
	}
	return TextMsgResponse_Success
}

// get cached messages
type GetAllCachedMessagesRequest struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllCachedMessagesRequest) Reset()         { *m = GetAllCachedMessagesRequest{} }
func (m *GetAllCachedMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllCachedMessagesRequest) ProtoMessage()    {}
func (*GetAllCachedMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{20}
}
func (m *GetAllCachedMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllCachedMessagesRequest.Unmarshal(m, b)
}
func (m *GetAllCachedMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllCachedMessagesRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllCachedMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllCachedMessagesRequest.Merge(dst, src)
}
func (m *GetAllCachedMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllCachedMessagesRequest.Size(m)
}
func (m *GetAllCachedMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllCachedMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllCachedMessagesRequest proto.InternalMessageInfo

func (m *GetAllCachedMessagesRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

// get cached messages
type GetAllCachedMessagesResponse struct {
	Header               *Header                             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result               GetAllCachedMessagesResponse_Result `protobuf:"varint,2,opt,name=result,proto3,enum=im.GetAllCachedMessagesResponse_Result" json:"result,omitempty"`
	Texts                []*Text                             `protobuf:"bytes,3,rep,name=texts,proto3" json:"texts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *GetAllCachedMessagesResponse) Reset()         { *m = GetAllCachedMessagesResponse{} }
func (m *GetAllCachedMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllCachedMessagesResponse) ProtoMessage()    {}
func (*GetAllCachedMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{21}
}
func (m *GetAllCachedMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllCachedMessagesResponse.Unmarshal(m, b)
}
func (m *GetAllCachedMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllCachedMessagesResponse.Marshal(b, m, deterministic)
}
func (dst *GetAllCachedMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllCachedMessagesResponse.Merge(dst, src)
}
func (m *GetAllCachedMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllCachedMessagesResponse.Size(m)
}
func (m *GetAllCachedMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllCachedMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllCachedMessagesResponse proto.InternalMessageInfo

func (m *GetAllCachedMessagesResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetAllCachedMessagesResponse) GetResult() GetAllCachedMessagesResponse_Result {
	if m != nil {
		return m.Result
	}
	return GetAllCachedMessagesResponse_Success
}

func (m *GetAllCachedMessagesResponse) GetTexts() []*Text {
	if m != nil {
		return m.Texts
	}
	return nil
}

// something like, i'm editing
// busy,, don't disturb etc
// already read
// msg success deliveried
type ActionMsg struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// support self-define
	ActionType           int32    `protobuf:"varint,2,opt,name=actionType,proto3" json:"actionType,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionMsg) Reset()         { *m = ActionMsg{} }
func (m *ActionMsg) String() string { return proto.CompactTextString(m) }
func (*ActionMsg) ProtoMessage()    {}
func (*ActionMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{22}
}
func (m *ActionMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionMsg.Unmarshal(m, b)
}
func (m *ActionMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionMsg.Marshal(b, m, deterministic)
}
func (dst *ActionMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionMsg.Merge(dst, src)
}
func (m *ActionMsg) XXX_Size() int {
	return xxx_messageInfo_ActionMsg.Size(m)
}
func (m *ActionMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ActionMsg proto.InternalMessageInfo

func (m *ActionMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ActionMsg) GetActionType() int32 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

func (m *ActionMsg) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type NotificationFriendRequestMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	HelloMsg             string   `protobuf:"bytes,3,opt,name=helloMsg,proto3" json:"helloMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationFriendRequestMsg) Reset()         { *m = NotificationFriendRequestMsg{} }
func (m *NotificationFriendRequestMsg) String() string { return proto.CompactTextString(m) }
func (*NotificationFriendRequestMsg) ProtoMessage()    {}
func (*NotificationFriendRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{23}
}
func (m *NotificationFriendRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationFriendRequestMsg.Unmarshal(m, b)
}
func (m *NotificationFriendRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationFriendRequestMsg.Marshal(b, m, deterministic)
}
func (dst *NotificationFriendRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationFriendRequestMsg.Merge(dst, src)
}
func (m *NotificationFriendRequestMsg) XXX_Size() int {
	return xxx_messageInfo_NotificationFriendRequestMsg.Size(m)
}
func (m *NotificationFriendRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationFriendRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationFriendRequestMsg proto.InternalMessageInfo

func (m *NotificationFriendRequestMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NotificationFriendRequestMsg) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *NotificationFriendRequestMsg) GetHelloMsg() string {
	if m != nil {
		return m.HelloMsg
	}
	return ""
}

type NotificationApproveMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationApproveMsg) Reset()         { *m = NotificationApproveMsg{} }
func (m *NotificationApproveMsg) String() string { return proto.CompactTextString(m) }
func (*NotificationApproveMsg) ProtoMessage()    {}
func (*NotificationApproveMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5e35aea80b179cf, []int{24}
}
func (m *NotificationApproveMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationApproveMsg.Unmarshal(m, b)
}
func (m *NotificationApproveMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationApproveMsg.Marshal(b, m, deterministic)
}
func (dst *NotificationApproveMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationApproveMsg.Merge(dst, src)
}
func (m *NotificationApproveMsg) XXX_Size() int {
	return xxx_messageInfo_NotificationApproveMsg.Size(m)
}
func (m *NotificationApproveMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationApproveMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationApproveMsg proto.InternalMessageInfo

func (m *NotificationApproveMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NotificationApproveMsg) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*Header)(nil), "im.Header")
	proto.RegisterType((*HeartbeatMsg)(nil), "im.HeartbeatMsg")
	proto.RegisterType((*InfoMsg)(nil), "im.InfoMsg")
	proto.RegisterType((*LoginMsg1)(nil), "im.LoginMsg1")
	proto.RegisterType((*LoginMsg2)(nil), "im.LoginMsg2")
	proto.RegisterType((*LoginMsg3)(nil), "im.LoginMsg3")
	proto.RegisterType((*UserProfileRequestMsg)(nil), "im.UserProfileRequestMsg")
	proto.RegisterType((*UserProfileResponseMsg)(nil), "im.UserProfileResponseMsg")
	proto.RegisterType((*UpdateProfileRequestMsg)(nil), "im.UpdateProfileRequestMsg")
	proto.RegisterType((*UpdateProfileResponseMsg)(nil), "im.UpdateProfileResponseMsg")
	proto.RegisterType((*FriendRequestMsg)(nil), "im.FriendRequestMsg")
	proto.RegisterType((*FriendResponseMsg)(nil), "im.FriendResponseMsg")
	proto.RegisterType((*ApproveRequestMsg)(nil), "im.ApproveRequestMsg")
	proto.RegisterType((*ApproveResponseMsg)(nil), "im.ApproveResponseMsg")
	proto.RegisterType((*GetAllRequestsMsg)(nil), "im.GetAllRequestsMsg")
	proto.RegisterType((*Request)(nil), "im.Request")
	proto.RegisterType((*GetAllRequestsResponseMsg)(nil), "im.GetAllRequestsResponseMsg")
	proto.RegisterType((*Text)(nil), "im.Text")
	proto.RegisterType((*TextMsg)(nil), "im.TextMsg")
	proto.RegisterType((*TextMsgResponse)(nil), "im.TextMsgResponse")
	proto.RegisterType((*GetAllCachedMessagesRequest)(nil), "im.GetAllCachedMessagesRequest")
	proto.RegisterType((*GetAllCachedMessagesResponse)(nil), "im.GetAllCachedMessagesResponse")
	proto.RegisterType((*ActionMsg)(nil), "im.ActionMsg")
	proto.RegisterType((*NotificationFriendRequestMsg)(nil), "im.NotificationFriendRequestMsg")
	proto.RegisterType((*NotificationApproveMsg)(nil), "im.NotificationApproveMsg")
	proto.RegisterEnum("im.UserProfileResponseMsg_Result", UserProfileResponseMsg_Result_name, UserProfileResponseMsg_Result_value)
	proto.RegisterEnum("im.UpdateProfileResponseMsg_Result", UpdateProfileResponseMsg_Result_name, UpdateProfileResponseMsg_Result_value)
	proto.RegisterEnum("im.FriendResponseMsg_Result", FriendResponseMsg_Result_name, FriendResponseMsg_Result_value)
	proto.RegisterEnum("im.ApproveResponseMsg_Result", ApproveResponseMsg_Result_name, ApproveResponseMsg_Result_value)
	proto.RegisterEnum("im.GetAllRequestsResponseMsg_Result", GetAllRequestsResponseMsg_Result_name, GetAllRequestsResponseMsg_Result_value)
	proto.RegisterEnum("im.TextMsgResponse_Result", TextMsgResponse_Result_name, TextMsgResponse_Result_value)
	proto.RegisterEnum("im.GetAllCachedMessagesResponse_Result", GetAllCachedMessagesResponse_Result_name, GetAllCachedMessagesResponse_Result_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_c5e35aea80b179cf) }

var fileDescriptor_messages_c5e35aea80b179cf = []byte{
	// 864 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0xc7, 0x49, 0x9b, 0x34, 0x93, 0xf6, 0x9a, 0x18, 0x28, 0xe6, 0x08, 0x55, 0x58, 0x2a, 0xae,
	0x4f, 0x91, 0xc8, 0x81, 0xe0, 0x04, 0x12, 0x8a, 0x38, 0xa0, 0xd5, 0x91, 0xe8, 0x70, 0x92, 0x27,
	0x9e, 0x5c, 0x7b, 0x92, 0xac, 0xf0, 0xbf, 0xee, 0x6e, 0xa2, 0xcb, 0x47, 0xe1, 0x1b, 0xf0, 0x8e,
	0xc4, 0x07, 0x80, 0x47, 0x24, 0x3e, 0x13, 0x5a, 0x67, 0x9d, 0xd8, 0x7b, 0xee, 0x9d, 0x73, 0xd7,
	0xb7, 0xcc, 0x78, 0xe6, 0xb7, 0xb3, 0xbf, 0xf9, 0xed, 0xce, 0x06, 0x1e, 0x04, 0xc8, 0xb9, 0x33,
	0x47, 0xde, 0x8b, 0x59, 0x24, 0x22, 0xb3, 0x42, 0x03, 0x72, 0x01, 0xb5, 0x2b, 0x74, 0x3c, 0x64,
	0xe6, 0x43, 0x38, 0x72, 0x17, 0xe8, 0xfe, 0x36, 0x5e, 0x06, 0x96, 0xd1, 0x35, 0x2e, 0x4f, 0xec,
	0xad, 0x4d, 0xfa, 0x70, 0x7c, 0x85, 0x0e, 0x13, 0x37, 0xe8, 0x88, 0x21, 0x9f, 0x9b, 0x04, 0x6a,
	0x8b, 0x24, 0x2b, 0x89, 0x6c, 0xf6, 0xa1, 0x47, 0x83, 0xde, 0x06, 0xc7, 0x56, 0x5f, 0xc8, 0x00,
	0xea, 0xd7, 0xe1, 0x2c, 0x2a, 0x19, 0x6e, 0x9a, 0x70, 0x20, 0xf0, 0x85, 0xb0, 0x2a, 0x5d, 0xe3,
	0xb2, 0x61, 0x27, 0xbf, 0xc9, 0x10, 0x1a, 0x3f, 0x47, 0x73, 0x1a, 0x0e, 0xf9, 0xfc, 0xf3, 0x52,
	0x20, 0x1d, 0x68, 0xc4, 0xcb, 0x1b, 0x9f, 0xba, 0xcf, 0x70, 0xad, 0x90, 0x76, 0x0e, 0x32, 0xdd,
	0xc1, 0xf5, 0x4b, 0xc1, 0x5d, 0xc0, 0x09, 0x86, 0x2e, 0x5b, 0xc7, 0x02, 0xbd, 0x49, 0x5a, 0xdc,
	0xb1, 0x9d, 0x77, 0x66, 0x61, 0x1f, 0x97, 0x85, 0xf5, 0xb0, 0x00, 0x36, 0xe7, 0x24, 0x63, 0x78,
	0x7f, 0xca, 0x91, 0x3d, 0x67, 0xd1, 0x8c, 0xfa, 0x68, 0xe3, 0xed, 0x12, 0x79, 0x59, 0xf2, 0xcd,
	0x33, 0xa8, 0x2d, 0x39, 0xb2, 0xeb, 0xa7, 0x8a, 0x05, 0x65, 0x91, 0x7f, 0x2a, 0x70, 0x96, 0x43,
	0xe5, 0x71, 0x14, 0x72, 0x2c, 0x0b, 0xfb, 0x04, 0x6a, 0x0c, 0xf9, 0xd2, 0xdf, 0x94, 0xfc, 0xa0,
	0xff, 0x89, 0x8c, 0x29, 0xc6, 0xeb, 0xd9, 0x49, 0xa0, 0xad, 0x12, 0x32, 0x15, 0x55, 0xb3, 0x15,
	0xe5, 0x5b, 0x76, 0xa0, 0xb5, 0xcc, 0xec, 0x42, 0xd3, 0xa3, 0x3c, 0xf6, 0x9d, 0xf5, 0xc8, 0x09,
	0xd0, 0x3a, 0x4c, 0xbe, 0x67, 0x5d, 0x49, 0x04, 0x72, 0x97, 0xd1, 0x58, 0xd0, 0x28, 0xb4, 0x6a,
	0x2a, 0x62, 0xe7, 0x92, 0x2b, 0x3b, 0x2b, 0x47, 0x38, 0xcc, 0xaa, 0x27, 0x3c, 0x2b, 0x8b, 0x7c,
	0x0d, 0xb5, 0x4d, 0x8d, 0x66, 0x13, 0xea, 0xe3, 0xa5, 0xeb, 0x22, 0xe7, 0xad, 0x77, 0xcc, 0x16,
	0x1c, 0x8f, 0xa2, 0xe7, 0xc8, 0x02, 0xca, 0x39, 0x8d, 0xc2, 0x96, 0x61, 0x9e, 0x42, 0x73, 0x1a,
	0xf2, 0x18, 0x5d, 0x3a, 0xa3, 0xe8, 0xb5, 0x2a, 0xe4, 0x77, 0x03, 0x3e, 0x98, 0xc6, 0x9e, 0x23,
	0xf0, 0xcd, 0xba, 0xa3, 0xed, 0xaa, 0xf2, 0xda, 0x5d, 0x55, 0x5f, 0xb5, 0xab, 0x83, 0xdc, 0xae,
	0xfe, 0x32, 0xc0, 0xd2, 0x6a, 0xdb, 0xaf, 0xc7, 0xdf, 0x68, 0x3d, 0xfe, 0x34, 0xe9, 0xf1, 0x1d,
	0x88, 0x5a, 0x97, 0xc9, 0x93, 0x62, 0x4e, 0xdb, 0x70, 0x22, 0x55, 0x32, 0x8a, 0xc4, 0x0f, 0x2f,
	0x28, 0x17, 0xbc, 0x88, 0xd4, 0x15, 0xb4, 0x7e, 0x64, 0x14, 0x43, 0x6f, 0x4f, 0x32, 0x09, 0x1c,
	0xcf, 0x92, 0xbc, 0x69, 0x56, 0xf0, 0x39, 0x9f, 0xbc, 0xdb, 0x16, 0xe8, 0xfb, 0xf2, 0x32, 0x52,
	0x5c, 0x6e, 0x6d, 0xf2, 0x87, 0x01, 0xed, 0x74, 0xe1, 0xfd, 0x98, 0xfa, 0x42, 0x63, 0xaa, 0x23,
	0x63, 0x5e, 0x82, 0xba, 0x47, 0x8a, 0x7e, 0x85, 0xf6, 0x20, 0x8e, 0x59, 0xb4, 0xc2, 0xfb, 0xe7,
	0x88, 0xfc, 0x6d, 0x80, 0xb9, 0x45, 0xdf, 0x8f, 0x88, 0x2f, 0x35, 0x22, 0x3e, 0x96, 0x31, 0x2f,
	0x63, 0xe9, 0x4c, 0xfc, 0x52, 0xcc, 0xc4, 0x7b, 0xd0, 0x52, 0xdb, 0xcb, 0x92, 0xf1, 0x2e, 0x9c,
	0x0e, 0x7c, 0x86, 0x8e, 0xb7, 0x56, 0xc0, 0x5e, 0xab, 0xa2, 0x33, 0x54, 0x25, 0x5f, 0x41, 0xfb,
	0x27, 0x14, 0x03, 0xdf, 0x57, 0x08, 0xbc, 0xec, 0xb4, 0xba, 0x85, 0xba, 0x4a, 0x91, 0x27, 0x6b,
	0xc6, 0xa2, 0xe0, 0xfa, 0x69, 0x12, 0xde, 0xb0, 0x95, 0x95, 0x13, 0x51, 0x25, 0x2f, 0x22, 0xf3,
	0x1c, 0x80, 0xf2, 0xb4, 0xb0, 0x44, 0x62, 0x47, 0x76, 0xc6, 0x93, 0x4c, 0x37, 0x1a, 0xa0, 0xba,
	0xe0, 0x92, 0xdf, 0xe4, 0x3f, 0x03, 0x3e, 0xcc, 0x17, 0xbb, 0x2f, 0xef, 0xdf, 0x6a, 0xbc, 0x5f,
	0xc8, 0x98, 0x3b, 0x21, 0xf5, 0x1b, 0xf9, 0x11, 0x1c, 0x31, 0x15, 0x65, 0x55, 0xbb, 0xd5, 0xcb,
	0x66, 0xbf, 0x29, 0xf3, 0x55, 0xa6, 0xbd, 0xfd, 0x48, 0x3e, 0x2b, 0xee, 0x93, 0x46, 0xbe, 0x41,
	0x26, 0x70, 0x20, 0x27, 0x97, 0x69, 0x41, 0xdd, 0x8d, 0x42, 0x81, 0xa1, 0x50, 0x0c, 0xa6, 0xe6,
	0x76, 0x08, 0x78, 0xb9, 0xb1, 0xe4, 0x49, 0x6a, 0xc7, 0x18, 0x7a, 0x13, 0x49, 0x91, 0x3a, 0x9f,
	0xa9, 0x4d, 0x9e, 0x41, 0x5d, 0xa2, 0x96, 0xe5, 0xa4, 0x93, 0x79, 0x47, 0x34, 0xfb, 0x47, 0x32,
	0x42, 0xa6, 0xab, 0x17, 0xc5, 0x9f, 0x06, 0x9c, 0x2a, 0xb4, 0x94, 0x99, 0x52, 0xa8, 0x7d, 0x8d,
	0xe9, 0x87, 0x29, 0x6e, 0x06, 0x48, 0x97, 0xf7, 0x55, 0xe9, 0x83, 0x7e, 0x02, 0x8d, 0x51, 0x24,
	0x36, 0x37, 0x47, 0x91, 0xaa, 0x07, 0xf0, 0xd1, 0xa6, 0xab, 0xdf, 0x3b, 0xee, 0x02, 0xbd, 0xa1,
	0x7a, 0xc6, 0xa5, 0x82, 0x2d, 0xa3, 0xef, 0x7f, 0x0d, 0xe8, 0x14, 0x63, 0xec, 0xc1, 0xc2, 0x77,
	0x1a, 0x0b, 0x8f, 0x76, 0x7a, 0x2b, 0x46, 0xd5, 0x25, 0x77, 0x0e, 0x87, 0xb2, 0x0d, 0xa9, 0xde,
	0x76, 0xdd, 0xd9, 0xb8, 0x4b, 0x2b, 0xed, 0x16, 0x1a, 0x03, 0x57, 0x8e, 0xc1, 0xb2, 0xaa, 0x38,
	0x07, 0x70, 0x92, 0x84, 0xc9, 0x3a, 0xde, 0x0c, 0xdc, 0x43, 0x3b, 0xe3, 0x79, 0xfd, 0xbc, 0x25,
	0x2b, 0xe8, 0x8c, 0x22, 0x41, 0x67, 0xd4, 0x75, 0xa4, 0xfd, 0x46, 0xa3, 0xea, 0x8e, 0x57, 0xd9,
	0x2b, 0xc7, 0xd3, 0x04, 0xce, 0xb2, 0xeb, 0xaa, 0x1b, 0xe5, 0x2d, 0x57, 0xbc, 0xa9, 0x25, 0xff,
	0x00, 0x1e, 0xff, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xf5, 0x1d, 0xec, 0x13, 0x0c, 0x00, 0x00,
}
