// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package im

/*
protoc --go_out=. message.proto
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateProfileResponseMsg_Result int32

const (
	UpdateProfileResponseMsg_Success       UpdateProfileResponseMsg_Result = 0
	UpdateProfileResponseMsg_UserNotExists UpdateProfileResponseMsg_Result = 1
	UpdateProfileResponseMsg_Unspecified   UpdateProfileResponseMsg_Result = 2
)

var UpdateProfileResponseMsg_Result_name = map[int32]string{
	0: "Success",
	1: "UserNotExists",
	2: "Unspecified",
}
var UpdateProfileResponseMsg_Result_value = map[string]int32{
	"Success":       0,
	"UserNotExists": 1,
	"Unspecified":   2,
}

func (x UpdateProfileResponseMsg_Result) String() string {
	return proto.EnumName(UpdateProfileResponseMsg_Result_name, int32(x))
}
func (UpdateProfileResponseMsg_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{8, 0}
}

type FriendResponseMsg_Result int32

const (
	FriendResponseMsg_Success       FriendResponseMsg_Result = 0
	FriendResponseMsg_UserNotExists FriendResponseMsg_Result = 1
	FriendResponseMsg_Unspecified   FriendResponseMsg_Result = 2
)

var FriendResponseMsg_Result_name = map[int32]string{
	0: "Success",
	1: "UserNotExists",
	2: "Unspecified",
}
var FriendResponseMsg_Result_value = map[string]int32{
	"Success":       0,
	"UserNotExists": 1,
	"Unspecified":   2,
}

func (x FriendResponseMsg_Result) String() string {
	return proto.EnumName(FriendResponseMsg_Result_name, int32(x))
}
func (FriendResponseMsg_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{10, 0}
}

type ApproveResponseMsg_Result int32

const (
	ApproveResponseMsg_Success          ApproveResponseMsg_Result = 0
	ApproveResponseMsg_RequestNotExists ApproveResponseMsg_Result = 1
	ApproveResponseMsg_AlreadyApproved  ApproveResponseMsg_Result = 2
	ApproveResponseMsg_Unspecified      ApproveResponseMsg_Result = 3
)

var ApproveResponseMsg_Result_name = map[int32]string{
	0: "Success",
	1: "RequestNotExists",
	2: "AlreadyApproved",
	3: "Unspecified",
}
var ApproveResponseMsg_Result_value = map[string]int32{
	"Success":          0,
	"RequestNotExists": 1,
	"AlreadyApproved":  2,
	"Unspecified":      3,
}

func (x ApproveResponseMsg_Result) String() string {
	return proto.EnumName(ApproveResponseMsg_Result_name, int32(x))
}
func (ApproveResponseMsg_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{12, 0}
}

type Header struct {
	// address base58 encoded
	CheckSum             uint32   `protobuf:"varint,1,opt,name=checkSum,proto3" json:"checkSum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetCheckSum() uint32 {
	if m != nil {
		return m.CheckSum
	}
	return 0
}

type InfoMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoMsg) Reset()         { *m = InfoMsg{} }
func (m *InfoMsg) String() string { return proto.CompactTextString(m) }
func (*InfoMsg) ProtoMessage()    {}
func (*InfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{1}
}
func (m *InfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoMsg.Unmarshal(m, b)
}
func (m *InfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoMsg.Marshal(b, m, deterministic)
}
func (dst *InfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoMsg.Merge(dst, src)
}
func (m *InfoMsg) XXX_Size() int {
	return xxx_messageInfo_InfoMsg.Size(m)
}
func (m *InfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InfoMsg proto.InternalMessageInfo

func (m *InfoMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *InfoMsg) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type LoginMsg1 struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMsg1) Reset()         { *m = LoginMsg1{} }
func (m *LoginMsg1) String() string { return proto.CompactTextString(m) }
func (*LoginMsg1) ProtoMessage()    {}
func (*LoginMsg1) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{2}
}
func (m *LoginMsg1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsg1.Unmarshal(m, b)
}
func (m *LoginMsg1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsg1.Marshal(b, m, deterministic)
}
func (dst *LoginMsg1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsg1.Merge(dst, src)
}
func (m *LoginMsg1) XXX_Size() int {
	return xxx_messageInfo_LoginMsg1.Size(m)
}
func (m *LoginMsg1) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsg1.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsg1 proto.InternalMessageInfo

func (m *LoginMsg1) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LoginMsg1) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type LoginMsg2 struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EncryptedText        []byte   `protobuf:"bytes,2,opt,name=encryptedText,proto3" json:"encryptedText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMsg2) Reset()         { *m = LoginMsg2{} }
func (m *LoginMsg2) String() string { return proto.CompactTextString(m) }
func (*LoginMsg2) ProtoMessage()    {}
func (*LoginMsg2) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{3}
}
func (m *LoginMsg2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsg2.Unmarshal(m, b)
}
func (m *LoginMsg2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsg2.Marshal(b, m, deterministic)
}
func (dst *LoginMsg2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsg2.Merge(dst, src)
}
func (m *LoginMsg2) XXX_Size() int {
	return xxx_messageInfo_LoginMsg2.Size(m)
}
func (m *LoginMsg2) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsg2.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsg2 proto.InternalMessageInfo

func (m *LoginMsg2) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LoginMsg2) GetEncryptedText() []byte {
	if m != nil {
		return m.EncryptedText
	}
	return nil
}

// for test usage
type LoginMsg3 struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	DecryptedText        []byte   `protobuf:"bytes,2,opt,name=decryptedText,proto3" json:"decryptedText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMsg3) Reset()         { *m = LoginMsg3{} }
func (m *LoginMsg3) String() string { return proto.CompactTextString(m) }
func (*LoginMsg3) ProtoMessage()    {}
func (*LoginMsg3) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{4}
}
func (m *LoginMsg3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsg3.Unmarshal(m, b)
}
func (m *LoginMsg3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsg3.Marshal(b, m, deterministic)
}
func (dst *LoginMsg3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsg3.Merge(dst, src)
}
func (m *LoginMsg3) XXX_Size() int {
	return xxx_messageInfo_LoginMsg3.Size(m)
}
func (m *LoginMsg3) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsg3.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsg3 proto.InternalMessageInfo

func (m *LoginMsg3) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LoginMsg3) GetDecryptedText() []byte {
	if m != nil {
		return m.DecryptedText
	}
	return nil
}

type UserProfileRequestMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfileRequestMsg) Reset()         { *m = UserProfileRequestMsg{} }
func (m *UserProfileRequestMsg) String() string { return proto.CompactTextString(m) }
func (*UserProfileRequestMsg) ProtoMessage()    {}
func (*UserProfileRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{5}
}
func (m *UserProfileRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileRequestMsg.Unmarshal(m, b)
}
func (m *UserProfileRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileRequestMsg.Marshal(b, m, deterministic)
}
func (dst *UserProfileRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileRequestMsg.Merge(dst, src)
}
func (m *UserProfileRequestMsg) XXX_Size() int {
	return xxx_messageInfo_UserProfileRequestMsg.Size(m)
}
func (m *UserProfileRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileRequestMsg proto.InternalMessageInfo

func (m *UserProfileRequestMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UserProfileRequestMsg) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UserProfileResponseMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	PublicKey            string   `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	DisplayName          string   `protobuf:"bytes,4,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Discription          string   `protobuf:"bytes,5,opt,name=discription,proto3" json:"discription,omitempty"`
	Avatar               []byte   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfileResponseMsg) Reset()         { *m = UserProfileResponseMsg{} }
func (m *UserProfileResponseMsg) String() string { return proto.CompactTextString(m) }
func (*UserProfileResponseMsg) ProtoMessage()    {}
func (*UserProfileResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{6}
}
func (m *UserProfileResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileResponseMsg.Unmarshal(m, b)
}
func (m *UserProfileResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileResponseMsg.Marshal(b, m, deterministic)
}
func (dst *UserProfileResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileResponseMsg.Merge(dst, src)
}
func (m *UserProfileResponseMsg) XXX_Size() int {
	return xxx_messageInfo_UserProfileResponseMsg.Size(m)
}
func (m *UserProfileResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileResponseMsg proto.InternalMessageInfo

func (m *UserProfileResponseMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UserProfileResponseMsg) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserProfileResponseMsg) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *UserProfileResponseMsg) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UserProfileResponseMsg) GetDiscription() string {
	if m != nil {
		return m.Discription
	}
	return ""
}

func (m *UserProfileResponseMsg) GetAvatar() []byte {
	if m != nil {
		return m.Avatar
	}
	return nil
}

type UpdateProfileRequestMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Discription          string   `protobuf:"bytes,3,opt,name=discription,proto3" json:"discription,omitempty"`
	Avatar               []byte   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProfileRequestMsg) Reset()         { *m = UpdateProfileRequestMsg{} }
func (m *UpdateProfileRequestMsg) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileRequestMsg) ProtoMessage()    {}
func (*UpdateProfileRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{7}
}
func (m *UpdateProfileRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileRequestMsg.Unmarshal(m, b)
}
func (m *UpdateProfileRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileRequestMsg.Marshal(b, m, deterministic)
}
func (dst *UpdateProfileRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileRequestMsg.Merge(dst, src)
}
func (m *UpdateProfileRequestMsg) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileRequestMsg.Size(m)
}
func (m *UpdateProfileRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileRequestMsg proto.InternalMessageInfo

func (m *UpdateProfileRequestMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UpdateProfileRequestMsg) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UpdateProfileRequestMsg) GetDiscription() string {
	if m != nil {
		return m.Discription
	}
	return ""
}

func (m *UpdateProfileRequestMsg) GetAvatar() []byte {
	if m != nil {
		return m.Avatar
	}
	return nil
}

type UpdateProfileResponseMsg struct {
	Header               *Header                         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result               UpdateProfileResponseMsg_Result `protobuf:"varint,2,opt,name=result,proto3,enum=im.UpdateProfileResponseMsg_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateProfileResponseMsg) Reset()         { *m = UpdateProfileResponseMsg{} }
func (m *UpdateProfileResponseMsg) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileResponseMsg) ProtoMessage()    {}
func (*UpdateProfileResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{8}
}
func (m *UpdateProfileResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileResponseMsg.Unmarshal(m, b)
}
func (m *UpdateProfileResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileResponseMsg.Marshal(b, m, deterministic)
}
func (dst *UpdateProfileResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileResponseMsg.Merge(dst, src)
}
func (m *UpdateProfileResponseMsg) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileResponseMsg.Size(m)
}
func (m *UpdateProfileResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileResponseMsg proto.InternalMessageInfo

func (m *UpdateProfileResponseMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UpdateProfileResponseMsg) GetResult() UpdateProfileResponseMsg_Result {
	if m != nil {
		return m.Result
	}
	return UpdateProfileResponseMsg_Success
}

type FriendRequestMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	FriendUserID         string   `protobuf:"bytes,2,opt,name=friendUserID,proto3" json:"friendUserID,omitempty"`
	HelloMsg             string   `protobuf:"bytes,3,opt,name=helloMsg,proto3" json:"helloMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendRequestMsg) Reset()         { *m = FriendRequestMsg{} }
func (m *FriendRequestMsg) String() string { return proto.CompactTextString(m) }
func (*FriendRequestMsg) ProtoMessage()    {}
func (*FriendRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{9}
}
func (m *FriendRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRequestMsg.Unmarshal(m, b)
}
func (m *FriendRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRequestMsg.Marshal(b, m, deterministic)
}
func (dst *FriendRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRequestMsg.Merge(dst, src)
}
func (m *FriendRequestMsg) XXX_Size() int {
	return xxx_messageInfo_FriendRequestMsg.Size(m)
}
func (m *FriendRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRequestMsg proto.InternalMessageInfo

func (m *FriendRequestMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *FriendRequestMsg) GetFriendUserID() string {
	if m != nil {
		return m.FriendUserID
	}
	return ""
}

func (m *FriendRequestMsg) GetHelloMsg() string {
	if m != nil {
		return m.HelloMsg
	}
	return ""
}

type FriendResponseMsg struct {
	Header               *Header                  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result               FriendResponseMsg_Result `protobuf:"varint,2,opt,name=result,proto3,enum=im.FriendResponseMsg_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FriendResponseMsg) Reset()         { *m = FriendResponseMsg{} }
func (m *FriendResponseMsg) String() string { return proto.CompactTextString(m) }
func (*FriendResponseMsg) ProtoMessage()    {}
func (*FriendResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{10}
}
func (m *FriendResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendResponseMsg.Unmarshal(m, b)
}
func (m *FriendResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendResponseMsg.Marshal(b, m, deterministic)
}
func (dst *FriendResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendResponseMsg.Merge(dst, src)
}
func (m *FriendResponseMsg) XXX_Size() int {
	return xxx_messageInfo_FriendResponseMsg.Size(m)
}
func (m *FriendResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FriendResponseMsg proto.InternalMessageInfo

func (m *FriendResponseMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *FriendResponseMsg) GetResult() FriendResponseMsg_Result {
	if m != nil {
		return m.Result
	}
	return FriendResponseMsg_Success
}

type ApproveRequestMsg struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	FriendUserID         string   `protobuf:"bytes,2,opt,name=friendUserID,proto3" json:"friendUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveRequestMsg) Reset()         { *m = ApproveRequestMsg{} }
func (m *ApproveRequestMsg) String() string { return proto.CompactTextString(m) }
func (*ApproveRequestMsg) ProtoMessage()    {}
func (*ApproveRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{11}
}
func (m *ApproveRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveRequestMsg.Unmarshal(m, b)
}
func (m *ApproveRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveRequestMsg.Marshal(b, m, deterministic)
}
func (dst *ApproveRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveRequestMsg.Merge(dst, src)
}
func (m *ApproveRequestMsg) XXX_Size() int {
	return xxx_messageInfo_ApproveRequestMsg.Size(m)
}
func (m *ApproveRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveRequestMsg proto.InternalMessageInfo

func (m *ApproveRequestMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ApproveRequestMsg) GetFriendUserID() string {
	if m != nil {
		return m.FriendUserID
	}
	return ""
}

type ApproveResponseMsg struct {
	Header               *Header                   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result               ApproveResponseMsg_Result `protobuf:"varint,2,opt,name=result,proto3,enum=im.ApproveResponseMsg_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ApproveResponseMsg) Reset()         { *m = ApproveResponseMsg{} }
func (m *ApproveResponseMsg) String() string { return proto.CompactTextString(m) }
func (*ApproveResponseMsg) ProtoMessage()    {}
func (*ApproveResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_f717b218b35f3b82, []int{12}
}
func (m *ApproveResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveResponseMsg.Unmarshal(m, b)
}
func (m *ApproveResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveResponseMsg.Marshal(b, m, deterministic)
}
func (dst *ApproveResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveResponseMsg.Merge(dst, src)
}
func (m *ApproveResponseMsg) XXX_Size() int {
	return xxx_messageInfo_ApproveResponseMsg.Size(m)
}
func (m *ApproveResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveResponseMsg proto.InternalMessageInfo

func (m *ApproveResponseMsg) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ApproveResponseMsg) GetResult() ApproveResponseMsg_Result {
	if m != nil {
		return m.Result
	}
	return ApproveResponseMsg_Success
}

func init() {
	proto.RegisterType((*Header)(nil), "im.Header")
	proto.RegisterType((*InfoMsg)(nil), "im.InfoMsg")
	proto.RegisterType((*LoginMsg1)(nil), "im.LoginMsg1")
	proto.RegisterType((*LoginMsg2)(nil), "im.LoginMsg2")
	proto.RegisterType((*LoginMsg3)(nil), "im.LoginMsg3")
	proto.RegisterType((*UserProfileRequestMsg)(nil), "im.UserProfileRequestMsg")
	proto.RegisterType((*UserProfileResponseMsg)(nil), "im.UserProfileResponseMsg")
	proto.RegisterType((*UpdateProfileRequestMsg)(nil), "im.UpdateProfileRequestMsg")
	proto.RegisterType((*UpdateProfileResponseMsg)(nil), "im.UpdateProfileResponseMsg")
	proto.RegisterType((*FriendRequestMsg)(nil), "im.FriendRequestMsg")
	proto.RegisterType((*FriendResponseMsg)(nil), "im.FriendResponseMsg")
	proto.RegisterType((*ApproveRequestMsg)(nil), "im.ApproveRequestMsg")
	proto.RegisterType((*ApproveResponseMsg)(nil), "im.ApproveResponseMsg")
	proto.RegisterEnum("im.UpdateProfileResponseMsg_Result", UpdateProfileResponseMsg_Result_name, UpdateProfileResponseMsg_Result_value)
	proto.RegisterEnum("im.FriendResponseMsg_Result", FriendResponseMsg_Result_name, FriendResponseMsg_Result_value)
	proto.RegisterEnum("im.ApproveResponseMsg_Result", ApproveResponseMsg_Result_name, ApproveResponseMsg_Result_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_f717b218b35f3b82) }

var fileDescriptor_messages_f717b218b35f3b82 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x49, 0x5b, 0x32, 0x7a, 0xba, 0x6e, 0xa9, 0x81, 0x11, 0xa1, 0x21, 0x55, 0x66, 0x17,
	0xbb, 0xaa, 0x44, 0x07, 0x17, 0x88, 0xab, 0x4a, 0x80, 0x98, 0xa0, 0x13, 0xa4, 0xe4, 0x8a, 0xab,
	0x2c, 0x39, 0x6d, 0x2d, 0x92, 0xd8, 0xd8, 0x4e, 0xb5, 0x3e, 0x0a, 0x6f, 0xc0, 0x13, 0xf0, 0x00,
	0x3c, 0x00, 0xcf, 0x84, 0x92, 0xba, 0x5d, 0x93, 0x0d, 0x68, 0x61, 0x77, 0x3d, 0xc7, 0xbf, 0x3f,
	0x9f, 0x7e, 0xb2, 0x1c, 0xd8, 0x4b, 0x50, 0xa9, 0x60, 0x82, 0xaa, 0x27, 0x24, 0xd7, 0x9c, 0xd4,
	0x58, 0x42, 0x8f, 0xc0, 0x7e, 0x83, 0x41, 0x84, 0x92, 0x3c, 0x84, 0x3b, 0xe1, 0x14, 0xc3, 0xcf,
	0xa3, 0x2c, 0x71, 0xad, 0xae, 0x75, 0xdc, 0xf6, 0x56, 0x35, 0x1d, 0xc0, 0xce, 0x69, 0x3a, 0xe6,
	0x43, 0x35, 0x21, 0x14, 0xec, 0x69, 0xb1, 0xa1, 0x08, 0xb5, 0xfa, 0xd0, 0x63, 0x49, 0x6f, 0x81,
	0xf0, 0xcc, 0x0a, 0x21, 0xd0, 0xd0, 0x78, 0xa1, 0xdd, 0x5a, 0xd7, 0x3a, 0x6e, 0x7a, 0xc5, 0x6f,
	0x3a, 0x84, 0xe6, 0x3b, 0x3e, 0x61, 0xe9, 0x50, 0x4d, 0x9e, 0x6c, 0x04, 0x39, 0x84, 0xa6, 0xc8,
	0xce, 0x63, 0x16, 0xbe, 0xc5, 0xb9, 0x21, 0x5d, 0x36, 0xa8, 0x7f, 0x89, 0xeb, 0x6f, 0x84, 0x3b,
	0x82, 0x36, 0xa6, 0xa1, 0x9c, 0x0b, 0x8d, 0xd1, 0xc7, 0xe5, 0x70, 0xbb, 0x5e, 0xb9, 0xb9, 0x8e,
	0x3d, 0xd9, 0x14, 0x1b, 0xe1, 0x35, 0xd8, 0x52, 0x93, 0x8e, 0xe0, 0xbe, 0xaf, 0x50, 0xbe, 0x97,
	0x7c, 0xcc, 0x62, 0xf4, 0xf0, 0x4b, 0x86, 0x4a, 0x6f, 0x6a, 0xf3, 0x00, 0xec, 0x4c, 0xa1, 0x3c,
	0x7d, 0x69, 0x2c, 0x98, 0x8a, 0xfe, 0xb4, 0xe0, 0xa0, 0x44, 0x55, 0x82, 0xa7, 0x0a, 0xff, 0x13,
	0x5b, 0xf6, 0x5e, 0xaf, 0x78, 0x27, 0x5d, 0x68, 0x45, 0x4c, 0x89, 0x38, 0x98, 0x9f, 0x05, 0x09,
	0xba, 0x8d, 0x62, 0x7d, 0xbd, 0x65, 0x12, 0xa1, 0x64, 0x42, 0x33, 0x9e, 0xba, 0xb7, 0x57, 0x89,
	0x65, 0x2b, 0x3f, 0x39, 0x98, 0x05, 0x3a, 0x90, 0xae, 0x5d, 0xc8, 0x32, 0x15, 0xfd, 0x6a, 0xc1,
	0x03, 0x5f, 0x44, 0x81, 0xc6, 0x7f, 0x13, 0x55, 0x99, 0xad, 0xf6, 0xd7, 0xd9, 0xea, 0x7f, 0x9a,
	0xad, 0x51, 0x9a, 0xed, 0xbb, 0x05, 0x6e, 0x65, 0xb6, 0xed, 0x74, 0xbf, 0x00, 0x5b, 0xa2, 0xca,
	0xe2, 0xc5, 0x0d, 0xd9, 0xeb, 0x3f, 0xce, 0x33, 0xbf, 0x23, 0xf6, 0xbc, 0x22, 0xea, 0x99, 0x2d,
	0xf4, 0x39, 0xd8, 0x8b, 0x0e, 0x69, 0xc1, 0xce, 0x28, 0x0b, 0x43, 0x54, 0xca, 0xb9, 0x45, 0x3a,
	0xd0, 0xce, 0x2f, 0xc0, 0x19, 0xd7, 0xaf, 0x2e, 0x98, 0xd2, 0xca, 0xb1, 0xc8, 0x3e, 0xb4, 0xfc,
	0x54, 0x09, 0x0c, 0xd9, 0x98, 0x61, 0xe4, 0xd4, 0xe8, 0x0c, 0x9c, 0xd7, 0x92, 0x61, 0x1a, 0x6d,
	0x29, 0x93, 0xc2, 0xee, 0xb8, 0xd8, 0xe7, 0xaf, 0x5f, 0x92, 0x52, 0x2f, 0x7f, 0x32, 0xa6, 0x18,
	0xc7, 0xf9, 0xbb, 0x60, 0x5c, 0xae, 0x6a, 0xfa, 0xcd, 0x82, 0xce, 0xf2, 0xe0, 0xed, 0x4c, 0x3d,
	0xad, 0x98, 0x3a, 0xcc, 0x33, 0x57, 0x50, 0x37, 0xa8, 0xe8, 0x13, 0x74, 0x06, 0x42, 0x48, 0x3e,
	0xc3, 0x9b, 0x77, 0x44, 0x7f, 0x58, 0x40, 0x56, 0xf4, 0xed, 0x44, 0x3c, 0xab, 0x88, 0x78, 0x94,
	0x67, 0xae, 0xb2, 0xaa, 0x26, 0x3e, 0x5c, 0x6f, 0xe2, 0x1e, 0x38, 0xe6, 0xef, 0xad, 0xcb, 0xb8,
	0x0b, 0xfb, 0x83, 0x58, 0x62, 0x10, 0xcd, 0x0d, 0x38, 0x72, 0x6a, 0x55, 0x43, 0xf5, 0x73, 0xbb,
	0xf8, 0x60, 0x9c, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x67, 0x6a, 0x3d, 0x41, 0x42, 0x06, 0x00,
	0x00,
}
